### ISSUE TITLE
i see error  which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by tontheonelove** [SociallyIneptWeeb/AICoverGen#144]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

**Comment by JackismyShephard** [comment]
@tontheonelove  If you are on Windows, then you need to have Visual Studio Build tools installed in order to build wheels for fairseq. I think that might be your problem. If you want to avoid the hassle of installing Visual Studio Build tools, you could have a look at my fork of this project here: https://github.com/JackismyShephard/ultimate-rvc 😊
