### ISSUE TITLE
[Request] On-Off Function, Mono-Stereo

### ISSUE THREAD

**Issue by yammie02** [SociallyIneptWeeb/AICoverGen#52]
Hello! I am always grateful to you.
I'd like to ask if you can add additional functions.

In my case, I input my voice. (No music, no backup vocals) And I want a conversion without reverb. 

Could you please make it possible to turn on and off the music and backup vocal removal and reverb functions?

I also type in mono files, and the output is coming out in stereo. Could you add a function that can come out as a mono?

Thank you very much for your hard work.
(I'm a translator user, so I don't know what nuance my message is getting through, but only my thanks are genuine🥹)

**Comment by SociallyIneptWeeb** [comment]
It seems that in your case, you only need the voice conversion functionality. In that case, you can use the official RVC voice conversion GitHub which does just that. They also come with more advanced options since it's made specifically for voice conversion, while this repo integrates multiple steps into a pipeline. https://github.com/Mangio621/Mangio-RVC-Fork

**Comment by SociallyIneptWeeb** [comment]
You should be able to obtain only the AI vocals from the song output file directory tho. You can look through each audio file but I think it's the one with the extended filename with numbers

**Comment by yammie02** [comment]
thank you
It's a bit more complex ui, but it seems to work for me. thank you for telling me!

**Comment by SociallyIneptWeeb** [comment]
No prob
